/*
 * Short encouragement the mascot says now and then. Written for My Space (not
 * attributed quotes), so nothing is misquoted and nothing needs a network call.
 */

export type QuoteLang = 'vi' | 'en'

export const QUOTES: Record<QuoteLang, string[]> = {
  vi: [
    'Bắt đầu nhỏ thôi, miễn là bắt đầu.',
    'Một dòng hôm nay hơn trăm dòng “để mai”.',
    'Bạn không cần hoàn hảo, chỉ cần tiếp tục.',
    'Chậm mà đều vẫn là đang đi.',
    'Viết xấu trước, sửa đẹp sau.',
    'Hít một hơi thật sâu. Rồi làm tiếp.',
    'Mỗi chữ bạn gõ là một bước về phía trước.',
    'Hôm nay làm được một ít cũng là thắng.',
    'Nghỉ một chút không có nghĩa là bỏ cuộc.',
    'Ý tưởng hay thường đến sau ý tưởng dở.',
    'Tập trung vào việc ngay trước mắt thôi.',
    'Bạn đang làm tốt hơn bạn nghĩ đấy.',
    'Đừng so sánh chương 1 của mình với chương 20 của người khác.',
    'Cứ viết đi, trang trắng sợ bạn hơn bạn sợ nó.',
    'Một việc mỗi lúc. Thế là đủ.',
    'Tiến bộ quan trọng hơn hoàn hảo.',
    'Uống ngụm nước rồi làm tiếp nào.',
    'Hôm qua là bài học, hôm nay là cơ hội.',
    'Sự kiên nhẫn cũng là một kỹ năng.',
    'Bạn không cần biết hết đường, chỉ cần bước tiếp theo.',
    'Việc khó nhất thường là mở file ra. Bạn làm xong rồi đó.',
    'Nhỏ mà đều đặn sẽ thành lớn.',
    'Đừng quên tự khen mình một câu.',
    'Mệt thì nghỉ, đừng bỏ.',
    'Một bản nháp tệ vẫn tốt hơn một trang trống.',
    'Sáng tạo là cho phép mình thử sai.',
    'Chỉ cần tốt hơn hôm qua một chút.',
    'Làm từng chút một, núi cũng dời được.',
    'Tâm trí yên thì chữ tự đến.',
    'Bạn có quyền bắt đầu lại bất cứ lúc nào.',
    'Thành công là tổng của những việc nhỏ lặp lại.',
    'Cứ đi, đường sẽ rõ dần.',
    'Đừng đợi cảm hứng, hãy hẹn gặp nó.',
    'Tắt thông báo, bật tập trung.',
    'Mười phút tập trung đáng giá hơn một giờ lơ đãng.',
    'Sai thì sửa, có gì đâu.',
    'Việc bạn đang làm có ý nghĩa đấy.',
    'Hãy dịu dàng với chính mình hôm nay.',
    'Mỗi ngày một viên gạch.',
    'Chữ viết ra rồi mới biên tập được.',
    'Ý tưởng cần được viết xuống mới sống được.',
    'Bạn đã đi xa hơn lúc bắt đầu rồi.',
    'Không ai sinh ra đã giỏi, ai cũng từng tập.',
    'Hãy làm vì bạn thích, không phải vì ai nhìn.',
    'Gõ tiếp đi, tớ đang cổ vũ nè!',
    'Đôi khi xong còn hơn đẹp.',
    'Cơn lười sẽ qua, việc xong sẽ ở lại.',
    'Thả lỏng vai ra, bạn đang gồng đó.',
    'Một bước nhỏ vẫn là một bước.',
    'Đừng để sợ hãi viết thay bạn.',
    'Tò mò là nhiên liệu tốt nhất.',
    'Bạn không chậm, bạn đang cẩn thận.',
    'Rối thì viết ra, viết ra sẽ rõ.',
    'Ngày dài hay ngắn là do mình chọn làm gì.',
    'Chỉ cần xong trang này thôi.',
    'Tin vào quá trình.',
    'Việc lớn bắt đầu từ việc nhỏ làm tới nơi.',
    'Hôm nay bạn chăm chỉ ghê.',
    'Có tiến là có mừng.',
    'Nghĩ ít lại, viết nhiều lên.',
    'Bạn là người kể câu chuyện của mình.',
    'Đừng xóa vội, biết đâu câu đó hay.',
    'Khó khăn là dấu hiệu bạn đang lớn lên.',
    'Mọi chuyên gia đều từng là người mới.',
    'Cứ để ý tưởng chảy ra, lọc sau.',
    'Giữ nhịp là bí quyết.',
    'Đến được đây là đã giỏi rồi.',
    'Đứng dậy vươn vai một cái nào.',
    'Bạn không cần làm hết, chỉ cần làm tiếp.',
    'Hãy trân trọng những gì đã làm được.',
    'Một chút mỗi ngày, rất nhiều mỗi năm.',
    'Kiên trì đánh bại tài năng lười biếng.',
    'Không có gì phí nếu bạn học được điều gì đó.',
    'Tập trung là món quà bạn tặng tương lai.',
    'Đừng để hoàn hảo làm kẻ thù của tốt.',
    'Mỗi bản nháp đều đưa bạn gần hơn.',
    'Nghĩ bằng tay: viết ra đi.',
    'Bạn có mọi thứ cần để bắt đầu.',
    'Hôm nay là một ngày tốt để làm xong việc.',
    'Nhắm mắt 20 giây, thả lỏng, rồi tiếp.',
    'Hãy làm việc như thể không ai chấm điểm.',
    'Sự bền bỉ âm thầm rất đáng nể.',
    'Chuyện nhỏ làm tốt thành chuyện lớn.',
    'Đừng quên ăn uống đàng hoàng nha.',
    'Lời khen đầu tiên nên đến từ chính bạn.',
    'Mọi hành trình đều có đoạn đi bộ.',
    'Rõ ràng đến từ việc làm, không phải từ việc nghĩ mãi.',
    'Làm xong rồi hẵng làm đẹp.',
    'Bạn đang xây thứ gì đó đáng tự hào.',
    'Mỗi phút tập trung đều được cộng dồn.',
    'Sai một chữ, sửa một chữ. Nhẹ tênh.',
    'Hãy cho ý tưởng của bạn một cơ hội.',
    'Không cần nhanh, chỉ cần không dừng.',
    'Nền móng tốt thì nhà mới vững.',
    'Thấy bí thì đổi góc nhìn.',
    'Ghi lại, kẻo quên.',
    'Bạn làm được mà.',
    'Hôm nay học được gì mới chưa?',
    'Đôi khi tiến một bước cần lùi nửa bước.',
    'Việc khó cứ chia nhỏ ra.',
    'Mỗi ngày là một trang mới.',
    'Viết cho mình trước, cho người sau.',
    'Chuyên tâm là siêu năng lực hiếm.',
    'Đừng bỏ cuộc trước khi phép màu xảy ra.',
    'Khởi đầu vụng về vẫn là khởi đầu.',
    'Hãy tự hào vì bạn đã xuất hiện hôm nay.',
    'Có ý tưởng thì ghi ngay, đừng để trôi.',
    'Bình tĩnh, từng việc một.',
    'Bạn đang tiến bộ, dù chưa thấy.',
    'Thói quen tốt là món đầu tư có lãi.',
    'Hãy làm điều mà bạn của tương lai sẽ cảm ơn.',
    'Câu chữ đẹp đến từ nhiều lần sửa.',
    'Buông điện thoại, cầm ý tưởng.',
    'Ngồi thẳng lưng, thở đều, tiếp tục.',
    'Mọi thứ đều dễ hơn khi đã bắt đầu.',
    'Không ai thấy nỗ lực âm thầm, nhưng kết quả thì có.',
    'Lạc hướng thì quay lại mục tiêu ban đầu.',
    'Sự đơn giản cần can đảm.',
    'Chọn một việc quan trọng nhất hôm nay.',
    'Đừng làm nhiều, hãy làm đúng.',
    'Nhịp chậm cũng là một nhịp.',
    'Bạn không cô đơn trên con đường này.',
    'Thêm một đoạn nữa thôi.',
    'Đừng đánh giá bản nháp quá sớm.',
    'Ý tưởng lớn cần thời gian để chín.',
    'Chữ nào viết ra cũng có giá trị.',
    'Đi ngủ đúng giờ cũng là năng suất.',
    'Hãy biết ơn chính mình vì đã cố gắng.',
    'Dám bắt đầu là đã hơn nửa đường.',
    'Làm việc sâu, nghỉ ngơi thật.',
    'Tốt hơn một chút mỗi lần là đủ.',
    'Kỷ luật là tự do dài hạn.',
    'Đừng ngại hỏi, đừng ngại sai.',
    'Nếu mệt, hãy nhớ lý do bạn bắt đầu.',
    'Chỉ cần 5 phút, rồi tính tiếp.',
    'Nỗ lực hôm nay là nền cho ngày mai.',
    'Hãy để công việc tự nói.',
    'Viết ngắn thôi, nhưng viết thật.',
    'Không có gì là quá nhỏ để ăn mừng.',
    'Cứ làm, rồi sẽ quen tay.',
    'Mục tiêu rõ thì bước chân nhẹ.',
    'Đầu óc cần khoảng trống để sáng tạo.',
    'Hãy tin vào bản năng của bạn.',
    'Mọi thứ tuyệt vời đều từng là bản nháp.',
    'Một trang trống là một khả năng mới.',
    'Hôm nay không cần xuất sắc, chỉ cần có mặt.',
    'Việc gì khó thì làm trước.',
    'Hãy để sự tò mò dẫn đường.',
    'Đừng để một ngày tệ định nghĩa bạn.',
    'Thành quả đến từ sự lặp lại.',
    'Bạn đang làm điều mà nhiều người chỉ nghĩ.',
    'Đơn giản hóa, rồi đơn giản hóa tiếp.',
    'Tắt tab thừa đi cho nhẹ đầu.',
    'Hãy để câu chữ thở.',
    'Cảm hứng thích người chăm chỉ.',
    'Làm từ từ, nhưng làm cho chắc.',
    'Bạn xứng đáng có một buổi làm việc êm ả.',
    'Mỗi lần thử là một lần học.',
    'Đừng cố nhớ, hãy ghi lại.',
    'Thời gian bạn đầu tư sẽ không mất đi.',
    'Hãy cho phép mình chưa biết.',
    'Tập trung vào điều bạn kiểm soát được.',
    'Bạn đang viết nên chương hay nhất đấy.',
    'Đừng để tiếng ồn lấn át giọng mình.',
    'Nghỉ đúng lúc giúp đi xa hơn.',
    'Chỉ cần thêm một ý nữa.',
    'Hãy làm vì chính niềm vui của việc làm.',
    'Ít mà chất.',
    'Việc hôm nay, hôm nay xong.',
    'Giữ lửa nhỏ còn hơn đốt cháy rồi tắt.',
    'Hãy nhớ mỉm cười một cái.',
    'Suy nghĩ tích cực, hành động cụ thể.',
    'Chẳng có gì phải vội.',
    'Mỗi ngày bạn đều đang học.',
    'Nếu chưa xong, thì chưa phải là kết thúc.',
    'Can đảm là làm dù còn sợ.',
    'Cứ viết như đang kể cho bạn thân nghe.',
    'Mọi con đường dài đều có trạm nghỉ.',
    'Bạn đã từng vượt qua nhiều thứ khó hơn.',
    'Cẩn thận hôm nay, nhẹ nhàng ngày mai.',
    'Mỗi dòng code, mỗi câu chữ đều đáng.',
    'Đừng để việc nhỏ kéo dài thành việc lớn.',
    'Dọn dẹp một chút, đầu óc thoáng hơn.',
    'Bắt đầu từ điều bạn biết rõ nhất.',
    'Hãy tự hỏi: bước nhỏ nhất tiếp theo là gì?',
    'Cứ để trái tim dẫn chữ.',
    'Làm việc thông minh, nghỉ ngơi đầy đủ.',
    'Hoàn thành tốt hơn hoàn hảo.',
    'Đôi khi chỉ cần viết một câu thật lòng.',
    'Không ai đếm số lần bạn ngã, chỉ nhớ lúc bạn đứng dậy.',
    'Mỗi ngày tốt lên 1% là rất nhiều.',
    'Bạn không cần đi nhanh, chỉ cần đi đúng hướng.',
    'Những ngày bình thường làm nên điều phi thường.',
    'Để tâm vào hiện tại.',
    'Mọi câu hỏi đều là khởi đầu tốt.',
    'Kế hoạch tốt là kế hoạch được làm.',
    'Tin mình thêm một chút.',
    'Cứ thử, cùng lắm là học được gì đó.',
    'Tiếp tục là một hành động dũng cảm.',
    'Bạn đang tạo ra điều chưa từng có.',
    'Chữ ít mà ý nhiều.',
    'Đừng ngại làm lại từ đầu.',
    'Tập trung thì mọi thứ nhẹ hơn.',
    'Viết đi, rồi bạn sẽ thấy mình nghĩ gì.',
    'Việc nhỏ hôm nay, kết quả lớn ngày sau.',
    'Hãy làm như cách bạn muốn được nhớ đến.',
    'Nỗ lực không bao giờ phản bội bạn.',
    'Mọi thứ bắt đầu từ một ý nghĩ.',
    'Cho mình một tràng pháo tay nào!',
    'Thở ra hết lo lắng, hít vào tự tin.',
    'Không cần to tát, chỉ cần thật.',
    'Hãy để ngày hôm nay nhẹ nhàng.',
    'Thêm một chút kiên nhẫn nữa thôi.',
    'Bạn làm tốt lắm, thật đó.',
    'Tốt nhất là làm ngay bây giờ.',
    'Mỗi thói quen nhỏ là một lá phiếu cho con người bạn muốn trở thành.',
    'Dừng lại để nhìn xem mình đã đi bao xa.',
    'Cứ tò mò như một đứa trẻ.',
    'Đi chậm để không phải quay lại.',
    'Không có câu hỏi ngớ ngẩn.',
    'Hãy để mọi thứ đơn giản.',
    'Chuyện hôm nay, để hôm nay lo.',
    'Hãy biến việc khó thành thói quen.',
    'Mỗi phút đều có thể là khởi đầu mới.',
    'Tự tin là thứ được rèn qua hành động.',
    'Làm một việc thật tốt còn hơn mười việc dở.',
    'Rồi sẽ ổn thôi.',
    'Thế giới cần những gì bạn tạo ra.',
    'Hãy giữ nhiệt huyết như ngày đầu.',
    'Bình yên đến từ việc sắp xếp.',
    'Tớ tin bạn!',
    'Tiếp đi, sắp tới đích rồi.',
    'Mỗi ý tưởng đều cần một nơi để ở, đây là nơi đó.',
    'Làm hết sức, rồi buông nhẹ.',
    'Đừng quên ngắm trời một chút.',
    'Đã đến lúc uống nước rồi đó!',
    'Chăm chỉ không cần ồn ào.',
    'Mọi điều tốt đẹp cần thời gian.',
    'Hôm nay bạn sẽ tự hào về mình.',
    'Chỉ cần bắt đầu, phần còn lại sẽ theo.',
    'Chữ đầu tiên luôn khó nhất.',
    'Bạn đang làm chủ thời gian của mình.',
    'Hãy viết điều bạn muốn đọc.',
    'Không cần đủ, chỉ cần đều.',
    'Cảm ơn bạn vì đã không bỏ cuộc.',
    'Một ý tưởng tốt đáng được làm đến nơi.',
    'Sự tập trung là món quà quý.',
    'Đừng để ngày mai làm hộ việc hôm nay.',
    'Làm với cả trái tim.',
    'Mọi con đường đều bắt đầu bằng bước đầu tiên.',
    'Đừng đếm giờ, hãy làm giờ có ý nghĩa.',
    'Chữ của bạn có sức mạnh.',
    'Lúc nào cũng có thể học thêm.',
    'Hãy làm điều khiến bạn thấy sống động.',
    'Mọi thứ đều có thể sửa, trừ trang chưa viết.',
    'Một ngày không lãng phí là một ngày có học.',
    'Không có đường tắt, chỉ có đường đều.',
    'Hãy cho mình thời gian.',
    'Viết ra để thấy nhẹ lòng.',
    'Hãy để kết quả làm bạn bất ngờ.',
    'Ý chí nhỏ, lặp lại, thành sức mạnh.',
    'Tâm an, việc thành.',
    'Hãy nhớ: bạn đang làm vì điều gì đó quan trọng.',
    'Bạn không cần ai cho phép để bắt đầu.',
    'Cứ thong thả, tớ ở đây mà.',
    'Có công mài sắt, có ngày nên kim.',
    'Tích tiểu thành đại.',
    'Chậm mà chắc.',
    'Không thầy đố mày làm nên, nhưng tự học cũng giỏi lắm.',
    'Đi một ngày đàng, học một sàng khôn.',
    'Nước chảy đá mòn.',
    'Mọi sự khởi đầu đều khó.',
    'Thất bại là mẹ thành công.',
    'Hôm nay cố thêm chút, mai nhẹ thêm chút.',
    'Làm xong việc thì thưởng cho mình nha.',
    'Nhìn lại những gì đã viết, thấy chưa, nhiều ghê!',
    'Không có ý tưởng tệ, chỉ có ý tưởng chưa chín.',
    'Cứ để cho sự tò mò thắng nỗi sợ.',
    'Một chút ánh nắng, một chút tập trung.',
    'Bạn đang làm việc mà bạn của năm ngoái mơ ước.',
    'Hãy cứ là chính mình trong từng câu chữ.',
    'Nghỉ ngơi cũng là một phần của công việc.',
    'Hãy để hôm nay là một ngày đáng nhớ.',
    'Đừng quên: bạn đã tiến xa lắm rồi.',
    'Chúc bạn một buổi làm việc thật trôi chảy.',
    'Mỗi lần mở máy là một lần chọn lại chính mình.',
    'Làm chậm lại để nghe mình nghĩ gì.',
    'Một ý rõ ràng đáng giá hơn mười ý mơ hồ.',
    'Chữ tốt cần thời gian, bạn cũng vậy.',
    'Hôm nay chỉ cần hơn hôm qua một dòng.',
    'Đừng để deadline làm bạn quên thở.',
    'Sắp xếp xong, đầu nhẹ hẳn.',
    'Ý tưởng nào cũng cần một người đủ kiên nhẫn.',
    'Hãy để công việc trôi như dòng nước.',
    'Một buổi tập trung là một món quà.',
    'Bạn đang gieo hạt, mùa gặt sẽ đến.',
    'Viết thật, sống thật.',
    'Cứ đều đặn, kết quả sẽ tự tìm đến.',
    'Nhẹ nhàng thôi, nhưng đừng dừng lại.',
    'Cảm ơn bạn đã dành thời gian cho điều mình yêu.',
    'Mỗi ngày một chút, rồi sẽ thành thói quen.',
    'Hãy kiêu hãnh về những bản nháp đầu tiên.',
    'Dịu lại một nhịp, rồi bứt tốc.',
    'Nhìn xa, bước gần.',
    'Bạn là phiên bản tốt nhất khi được là chính mình.',
  ],
  en: [
    'Start small. Just start.',
    'One line today beats a page tomorrow.',
    'You don’t need perfect. You need next.',
    'Slow and steady is still moving.',
    'Write it messy, fix it later.',
    'Deep breath. Now keep going.',
    'Every word is a step forward.',
    'A little done is a win.',
    'Resting isn’t quitting.',
    'Good ideas often follow bad ones.',
    'Just the next thing. That’s all.',
    'You’re doing better than you think.',
    'Don’t compare your chapter 1 to someone’s chapter 20.',
    'The blank page is more scared of you.',
    'One thing at a time is enough.',
    'Progress over perfection.',
    'Sip some water, then carry on.',
    'Yesterday taught you. Today is yours.',
    'Patience is a skill too.',
    'You only need to see the next step.',
    'Opening the file was the hard part. Done.',
    'Small and steady grows big.',
    'Say one kind thing to yourself.',
    'Tired? Rest. Don’t stop.',
    'A rough draft beats an empty page.',
    'Creating means allowing mistakes.',
    'Just a bit better than yesterday.',
    'Bit by bit, mountains move.',
    'Quiet mind, easy words.',
    'You can begin again any time.',
    'Success is small things, repeated.',
    'Keep walking; the path gets clearer.',
    'Don’t wait for inspiration. Book a meeting with it.',
    'Notifications off. Focus on.',
    'Ten focused minutes beat an hour of drifting.',
    'Wrong? Fix it. No big deal.',
    'What you’re doing matters.',
    'Be gentle with yourself today.',
    'One brick a day.',
    'You can only edit words that exist.',
    'Ideas live once they’re written down.',
    'You’re already further than where you started.',
    'Nobody is born good at this. Everyone practised.',
    'Make it for you, not for the audience.',
    'Keep typing, I’m cheering!',
    'Sometimes done beats pretty.',
    'Laziness passes. Finished work stays.',
    'Drop your shoulders. You’re tensing up.',
    'A small step is still a step.',
    'Don’t let fear hold the pen.',
    'Curiosity is the best fuel.',
    'You’re not slow. You’re careful.',
    'Tangled? Write it out. It untangles.',
    'The day is as long as what you choose to do.',
    'Just finish this page.',
    'Trust the process.',
    'Big things start as small things finished.',
    'You’re on a roll today.',
    'Any progress is worth a smile.',
    'Think less, write more.',
    'You’re the one telling your story.',
    'Don’t delete it yet. It might be good.',
    'Hard means you’re growing.',
    'Every expert was once a beginner.',
    'Let ideas flow. Filter later.',
    'Rhythm is the secret.',
    'Getting here was already impressive.',
    'Stand up and stretch for a sec.',
    'You don’t have to do it all. Just the next bit.',
    'Notice what you’ve already done.',
    'A little a day, a lot a year.',
    'Steady effort beats lazy talent.',
    'Nothing is wasted if you learned something.',
    'Focus is a gift to future you.',
    'Don’t let perfect be the enemy of good.',
    'Every draft gets you closer.',
    'Think with your hands. Write it down.',
    'You have everything you need to start.',
    'Today is a fine day to finish something.',
    'Close your eyes for 20 seconds. Then go.',
    'Work like nobody’s grading.',
    'Quiet persistence is impressive.',
    'Small things done well become big things.',
    'Remember to eat something good.',
    'The first compliment should come from you.',
    'Every journey has walking parts.',
    'Clarity comes from doing, not endless thinking.',
    'Finish first, polish later.',
    'You’re building something to be proud of.',
    'Focused minutes add up.',
    'Wrong word? Change one word. Easy.',
    'Give your idea a chance.',
    'No need to be fast. Just don’t stop.',
    'Good foundations, solid house.',
    'Stuck? Change the angle.',
    'Write it down before it floats away.',
    'You’ve got this.',
    'Learned anything new today?',
    'Sometimes a step back is part of moving forward.',
    'Hard task? Slice it smaller.',
    'Every day is a new page.',
    'Write for yourself first.',
    'Deep focus is a rare superpower.',
    'Don’t quit right before it clicks.',
    'A clumsy start is still a start.',
    'Be proud you showed up today.',
    'Got an idea? Catch it now.',
    'Calm. One thing at a time.',
    'You’re improving, even if you can’t see it yet.',
    'Good habits pay interest.',
    'Do something future you will thank you for.',
    'Good sentences come from many edits.',
    'Put the phone down. Pick the idea up.',
    'Sit tall, breathe, continue.',
    'Everything is easier once started.',
    'Quiet effort shows up in the results.',
    'Lost? Go back to why you began.',
    'Simplicity takes courage.',
    'Pick the one thing that matters most today.',
    'Do less, but do it right.',
    'A slow beat is still a beat.',
    'You’re not alone on this road.',
    'Just one more paragraph.',
    'Don’t judge the draft too early.',
    'Big ideas need time to ripen.',
    'Every word you write counts.',
    'Going to bed on time is productive too.',
    'Thank yourself for trying.',
    'Starting is half the journey.',
    'Work deeply. Rest truly.',
    'A little better each time is enough.',
    'Discipline is long-term freedom.',
    'Don’t be afraid to ask, or to be wrong.',
    'Tired? Remember why you started.',
    'Just five minutes. Then decide.',
    'Today’s effort is tomorrow’s ground.',
    'Let the work speak.',
    'Write short, but write true.',
    'Nothing is too small to celebrate.',
    'Keep doing it. It gets familiar.',
    'Clear goal, light steps.',
    'A mind needs space to create.',
    'Trust your instincts.',
    'Everything great was once a draft.',
    'A blank page is a new possibility.',
    'Today you don’t need brilliant. Just present.',
    'Do the hard thing first.',
    'Let curiosity lead.',
    'One bad day doesn’t define you.',
    'Results come from repetition.',
    'You’re doing what many only think about.',
    'Simplify. Then simplify again.',
    'Close a few tabs. Clear your head.',
    'Let your sentences breathe.',
    'Inspiration likes hard workers.',
    'Take it slow, make it solid.',
    'You deserve a calm working session.',
    'Every try is a lesson.',
    'Don’t memorise. Write it down.',
    'Time you invest isn’t lost.',
    'It’s okay not to know yet.',
    'Focus on what you can control.',
    'You might be writing your best chapter.',
    'Don’t let noise drown your voice.',
    'Rest at the right time to go further.',
    'Just one more idea.',
    'Do it for the joy of doing it.',
    'Less, but better.',
    'Today’s task, done today.',
    'Keep a small flame rather than burn out.',
    'Remember to smile a little.',
    'Positive thoughts, concrete actions.',
    'No rush.',
    'You’re learning every day.',
    'Not done yet isn’t the end.',
    'Courage is doing it scared.',
    'Write like you’re telling a friend.',
    'Every long road has rest stops.',
    'You’ve made it through harder things.',
    'Careful today, easy tomorrow.',
    'Every line of code, every sentence counts.',
    'Don’t let small tasks grow big.',
    'Tidy a little. Think a lot clearer.',
    'Start with what you know best.',
    'Ask: what’s the smallest next step?',
    'Let your heart lead the words.',
    'Work smart, rest fully.',
    'Finished beats flawless.',
    'Sometimes one honest sentence is enough.',
    'Nobody counts the falls, only the getting up.',
    '1% better a day is a lot.',
    'Not fast. Just the right direction.',
    'Ordinary days build extraordinary things.',
    'Be here now.',
    'Every question is a good start.',
    'A good plan is one that gets done.',
    'Believe in yourself a little more.',
    'Try it. Worst case, you learn.',
    'Continuing is brave.',
    'You’re making something new.',
    'Fewer words, more meaning.',
    'Starting over is allowed.',
    'Focus makes everything lighter.',
    'Write, and find out what you think.',
    'Small work today, big results later.',
    'Work the way you’d like to be remembered.',
    'Effort never betrays you.',
    'Everything starts as a thought.',
    'Give yourself a round of applause!',
    'Breathe out worry, breathe in confidence.',
    'It doesn’t need to be grand. Just real.',
    'Let today be gentle.',
    'A little more patience.',
    'You’re doing great. Really.',
    'The best time is now.',
    'Every small habit is a vote for who you’re becoming.',
    'Pause and see how far you’ve come.',
    'Stay curious like a kid.',
    'Go slow so you don’t have to go back.',
    'There are no silly questions.',
    'Keep it simple.',
    'Today’s worries belong to today.',
    'Turn the hard thing into a habit.',
    'Any minute can be a fresh start.',
    'Confidence is built by doing.',
    'One thing done well beats ten done badly.',
    'It’ll be okay.',
    'The world needs what you make.',
    'Keep the spark of day one.',
    'Calm comes from order.',
    'I believe in you!',
    'Keep going, you’re nearly there.',
    'Every idea needs a home. This is it.',
    'Give your best, then let go.',
    'Look at the sky for a moment.',
    'Water break time!',
    'Hard work doesn’t need to be loud.',
    'Good things take time.',
    'You’ll be proud of yourself today.',
    'Begin, and the rest follows.',
    'The first word is always the hardest.',
    'You’re in charge of your time.',
    'Write what you’d want to read.',
    'Not enough, just steady.',
    'Thanks for not giving up.',
    'A good idea deserves to be finished.',
    'Focus is precious.',
    'Don’t let tomorrow do today’s job.',
    'Put your heart into it.',
    'Every road starts with one step.',
    'Don’t count hours. Make them count.',
    'Your words have power.',
    'There’s always more to learn.',
    'Do what makes you feel alive.',
    'Anything can be fixed, except the page never written.',
    'A day you learned something isn’t wasted.',
    'No shortcuts, just steady roads.',
    'Give yourself time.',
    'Write it out and feel lighter.',
    'Let the results surprise you.',
    'Small will, repeated, becomes strength.',
    'Calm mind, finished work.',
    'Remember: this matters.',
    'You don’t need permission to begin.',
    'Take your time, I’m right here.',
    'Drop by drop fills the pot.',
    'Little strokes fell great oaks.',
    'Rome wasn’t built in a day.',
    'Practice makes progress.',
    'Every master was once a disaster.',
    'Mistakes are proof you’re trying.',
    'Push a little today, float a little tomorrow.',
    'Done? Treat yourself.',
    'Look back at what you wrote. That’s a lot!',
    'No bad ideas, only unripe ones.',
    'Let curiosity beat fear.',
    'A bit of sunshine, a bit of focus.',
    'You’re doing what last-year-you dreamed of.',
    'Be yourself in every sentence.',
    'Rest is part of the work.',
    'Make today one to remember.',
    'Don’t forget: you’ve come a long way.',
    'Wishing you a smooth, easy session.',
    'Tiny progress is still progress.',
    'Your pace is the right pace.',
    'Messy middles are normal.',
    'Show up, even imperfectly.',
    'Consistency is quiet magic.',
    'You can do hard things.',
    'Proud of you for being here.',
    'Keep the words coming.',
    'Momentum loves a first step.',
    'Nice rhythm. Keep it up!',
    'Every session is a chance to choose yourself again.',
    'Slow down enough to hear your own thoughts.',
    'One clear idea beats ten fuzzy ones.',
    'Good words take time. So do you.',
    'Today, just one line more than yesterday.',
    'Don’t let a deadline make you forget to breathe.',
    'Sorted things, lighter head.',
    'You’re planting seeds. Harvest comes.',
    'Gentle, but don’t stop.',
    'Thanks for making time for what you love.',
    'Be proud of your first drafts.',
    'Look far, step near.',
    'You’re at your best being yourself.',
  ],
}

/** Picks without repeats until every line has been shown once. */
export function quoteBag(lang: QuoteLang) {
  let bag: string[] = []
  return () => {
    if (!bag.length) {
      bag = [...QUOTES[lang]]
      for (let i = bag.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1))
        ;[bag[i], bag[j]] = [bag[j], bag[i]]
      }
    }
    return bag.pop() as string
  }
}
